[package]
name = "palmera-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
futures = "0.3.31"
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.45.1", features = ["full"] }
