[package]
name = "table-management-example"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
palmera-database = { path = "../../palmera-database" }
sqlx = { version = "0.8.6", features = ["sqlite", "migrate", "runtime-tokio"] }
