services:
  db:
    image: postgres:17.4-alpine3.20
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  minio:
    image: bitnami/minio:2025.4.22-debian-12-r2
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-password
    volumes:
      - minio_data:/bitnami/minio/data
    command: [ "server", "/bitnami/minio/data", "--console-address", ":9001" ]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  db_data:
  minio_data:
